FROM node:22-alpine
# RUN npm install -g nodemon ts-node
WORKDIR /home/app
COPY package*.json ./
RUN npm install
EXPOSE 3000
# CMD ["nodemon", "--exec", "ts-node", "src/index.ts"]
CMD ["npm", "run", "dev"]